CREATE TABLE `accounts` (
	`steamid` INTEGER UNSIGNED NOT NULL,
	`discordid` VARCHAR(25) NOT NULL,
	`mention` VARCHAR(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `matches` (
	`format` INTEGER UNSIGNED NOT NULL,
	`matchid` VARCHAR(25) NOT NULL,
	`steamid` INTEGER UNSIGNED NOT NULL,
	`when` DATETIME NOT NULL,
	`region` INTEGER UNSIGNED NOT NULL,
	`lobby_type` INTEGER UNSIGNED NOT NULL,
	`game_mode` INTEGER UNSIGNED NOT NULL,
	`skill` INTEGER UNSIGNED NOT NULL,
	`solo` TINYINT UNSIGNED NOT NULL,
	`duration` INTEGER UNSIGNED NOT NULL,
	`side` TINYINT UNSIGNED NOT NULL,
	`winner` TINYINT UNSIGNED NOT NULL,
	`leaver` INTEGER UNSIGNED NOT NULL,
	`hero` INTEGER UNSIGNED NOT NULL,
	`level` INTEGER UNSIGNED NOT NULL,
	`kills` INTEGER UNSIGNED NOT NULL,
	`deaths` INTEGER UNSIGNED NOT NULL,
	`assists` INTEGER UNSIGNED NOT NULL,
	`gpm` INTEGER UNSIGNED NOT NULL,
	`xpm` INTEGER UNSIGNED NOT NULL,
	`hero_damage` INTEGER UNSIGNED NOT NULL,
	`tower_damage` INTEGER UNSIGNED NOT NULL,
	`hero_healing` INTEGER UNSIGNED NOT NULL,
	`randomed` TINYINT UNSIGNED NOT NULL,
	`dead_time` INTEGER UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
